name: Application E2E Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    # deploy to some where
    - name: Install dependencies
      working-directory: ./e2e_test
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install .
    - name: run test
      working-directory: ./order_system
      run: |
        tox

